### ISSUE TITLE
[Bug]: GROW simulator workflow crashed with ubx[2496] = -nan

### ISSUE THREAD

**Issue by samvanderzwan** [Nieuwe-Warmte-Nu/user_feedback#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

When running the simulator workflow from grow it crashes with the following error log:
RuntimeError: Error in Function::call for 'mysolver' [HighsInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'mysolver' [HighsInterface] at .../casadi/core/function.cpp:330:
.../casadi/core/conic.cpp:476: Assertion "lb <= ub && lb!=inf && ub!=-inf" failed:
Ill-posed problem detected: LBX[2496] <= UBX[2496] was violated. Got LBX[2496]=0 and UBX[2496] = -nan.
Will use log level LogLevel.INFO for logger nwnsdk
Starting
Which is not clear how to solve it.

[TEST2 with return network_GrowOptimized_GrowOptimized(4).esdl.txt](https://github.com/Nieuwe-Warmte-Nu/user_feedback/files/12831150/TEST2.with.return.network_GrowOptimized_GrowOptimized.4.esdl.txt)

### Steps to reproduce the problem

1. Load ESDL
2. Start simulator workflow
3. wait
4. See it is failed and check the log

### What should have happened?

Preferred solution is that the model is simulated. 
Second best is getting error back so you no what to change

### What browsers do you use to access the UI?

Mozilla Firefox

**Comment by jimrojerTNO** [comment]
@samvanderzwan can you share the non GROW_optimized ESDL too?

**Comment by samvanderzwan** [comment]
I will close this, since it is to long ago for me to find the esdl.
